name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm install -g bun
      - run: bun install
      - run: bun lint

  test:
    strategy:
      fail-fast: false
      matrix:
        nodeVersion: [20, 22, 24]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodeVersion }}
      - run: npm install -g bun
      - run: bun install
      - run: bun run test
